version: "3.8"

services:
    elasticsearch:
        image: elasticsearch:7.9.3
        container_name: elasticsearch
        hostname: elasticsearch
        environment:
            - "discovery.type=single-node"
        ports:
            - 9200:9200
        networks:
            - elknetwork
    kibana:
        image: kibana:7.9.3
        container_name: kibana
        hostname: kibana
        ports:
            - 8080:8080
        links:
            - elasticsearch:elasticsearch
        depends_on:
          - elasticsearch
        networks:
          - elknetwork
    logstash:
        image: logstash:7.9.3
        container_name: logstash
        hostname: logstash
        ports:
            - 9600:9600
        volumes:
          - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
        links:
            - elasticsearch:elasticsearch
        depends_on:
          - elasticsearch
        networks:
          - elknetwork
    httpd:
        image: httpd:latest
        depends_on:
        - logstash
        ports:
        - 80:80
        logging:
          driver: gelf
          options:
            gelf-address: "udp://localhost:80"
networks:
    elknetwork:
        driver: bridge
